### ISSUE TITLE
Manifest Should Follow Cargo's

### ISSUE THREAD

**Issue by playmer** [TrevorSundberg/ne#2]
This isn't too important, but considering it's early on in the spec, is there any reason for XML to be used for the manifest? Although I haven't used it much, it's likely that the manifest files could likely look a lot more like what rust's cargo uses:

https://doc.rust-lang.org/cargo/reference/manifest.html

I'm not sure if anyone would really enjoy dealing with human written XML, particularly the Linux/MacOS crowd.

**Comment by TrevorSundberg** [comment]
Originally I had it as YAML but changed my mind only because of the popularity of XML. Personally I don't like XML because of the duplication of elements for closing. I'd be in favor of anything else too, have you looked at YAML?

**Comment by playmer** [comment]
I think YAML would be a pretty good idea. I've heard good things and it seems pretty easily human writable for simple things.

**Comment by TrevorSundberg** [comment]
It's been switched to YAML
